version: '3.8'
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=PUBLIC_IP_OR_DOMAIN
      - SERVERPORT=51820
      - PEERS=2 # Number of clients (devices)
      - PEERDNS=auto # DNS for clients
      - INTERNAL_SUBNET=10.13.13.0 # Sub-network of VPN
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - vpn_network
    restart: unless-stopped

networks:
  vpn_network:
    external: true
